# Generated by Django 2.2 on 2019-09-16 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile_HeadPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headportrait_image', models.ImageField(blank=True, default='headportrait/default.png', null=True, upload_to=users.models.image_upload_to, verbose_name='用户头像')),
                ('height_field', models.IntegerField(default=160)),
                ('width_field', models.IntegerField(default=160)),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
