# Generated by Django 2.2 on 2019-09-16 19:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190916_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='headportrait',
            field=models.ImageField(default='headportrait/default.png', upload_to=users.models.image_upload_to, verbose_name='头像'),
        ),
    ]
