# Generated by Django 2.2 on 2019-09-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_order', '0007_auto_20190819_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder_Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_contents', models.TextField(blank=True, null=True, verbose_name='回复内容')),
                ('replay_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('replayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replayer', to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
                ('workorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoder_title', to='work_order.WorkOrder', verbose_name='工单标题')),
            ],
        ),
    ]
