# Generated by Django 2.2 on 2019-09-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0009_auto_20190906_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder_replay',
            old_name='workorder_id',
            new_name='title',
        ),
    ]
