# Generated by Django 2.2 on 2019-09-09 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_order', '0011_auto_20190909_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkOrder_Replay',
            new_name='WorkOrder_Reply',
        ),
    ]
