# Generated by Django 2.2 on 2019-09-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0012_auto_20190909_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='orderfiles/%Y/%m', verbose_name='工单附件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': 'workorder_file',
                'verbose_name_plural': 'workorder_file',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='files',
            field=models.ManyToManyField(related_name='files', to='work_order.WorkOrder_File', verbose_name='附件'),
        ),
    ]
