# Generated by Django 2.2 on 2019-09-11 10:47

from django.db import migrations, models
import work_order.models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0013_auto_20190910_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder_file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=work_order.models.file_upload_to, verbose_name='工单附件'),
        ),
    ]
