# Generated by Django 2.2 on 2019-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0014_auto_20190911_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder_file',
            name='filesize',
            field=models.CharField(max_length=100, null=True, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='workorder_file',
            name='filetype',
            field=models.CharField(max_length=100, null=True, verbose_name='文件类型'),
        ),
    ]
