# Generated by Django 2.2 on 2019-09-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0015_auto_20190912_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder_file',
            name='filesize',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='workorder_file',
            name='filetype',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='文件类型'),
        ),
    ]
