# Generated by Django 2.2 on 2019-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0016_auto_20190912_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder_file',
            options={'ordering': ['upload_time'], 'verbose_name': 'workorder_file', 'verbose_name_plural': 'workorder_file'},
        ),
    ]
