# Generated by Django 2.2 on 2019-09-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0019_workorder_reply_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='orderfiles',
        ),
    ]
